apiVersion: v1
kind: Pod
metadata:
  namespace: frontend
  name: nginx.pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14-alpine
      resources:
        limits:
          memory: 20Mi
          cpu: 0.2